# https://doc.traefik.io/traefik/reference/static-configuration/file/
# https://json.schemastore.org/traefik-v2.json
global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  insecure: true
  dashboard: true
  # debug: true

providers:
  docker:
    exposedByDefault: false
  # file:
  #   filename: ./file-conf.yaml
  #   watch: true
# entryPoints:
#   web:
#     address: ":80"
#   websecure:
#     address: ":443"
#   other:
#     address: ":9090"
